Repository 10up/wp_mock, pull requests merged in 2023-07, with the labels that each got.

#222 Update README.md (minor edits for grammar and content)
  README.md
Labels: Documentation

#216 Update dependencies and PhpStan return types
  composer.json
  composer.lock
  php/WP_Mock.php
  php/WP_Mock/API/function-mocks.php
  php/WP_Mock/Functions.php
  php/WP_Mock/Tools/TestCase.php
  phpstan-baseline.neon
Labels: Dependencies

#219 Add test coverage to handler and return sequence classes
  docs/usage/using-wp-mock.md
  php/WP_Mock.php
  php/WP_Mock/API/function-mocks.php
  php/WP_Mock/Functions.php
  php/WP_Mock/Functions/Handler.php
  php/WP_Mock/Functions/ReturnSequence.php
  php/WP_Mock/Handler.php
  php/WP_Mock/ReturnSequence.php
  phpstan-baseline.neon
  tests/Integration/WP_MockTest.php
  tests/Unit/WP_Mock/API/FunctionMocksTest.php
  tests/Unit/WP_Mock/Functions/HandlerTest.php
  tests/Unit/WP_Mock/Functions/ReturnSequenceTest.php
  tests/Unit/WP_Mock/FunctionsTest.php
  tests/Unit/WP_MockTest.php
  tests/WP_MockTestCase.php
Labels: Tests

#223 Add setInaccessiblePropertyValue helper method and update docs
  docs/tools/wp-mock-test-case.md
  php/WP_Mock/Traits/AccessInaccessibleClassMembersTrait.php
  tests/Unit/WP_Mock/FunctionsTest.php
  tests/Unit/WP_Mock/Traits/AccessInaccessibleClassMembersTraitTest.php
Labels: Enhancement, Documentation

#224 Fixes a bug that causes a responder not to run the intercepted method while testing an hook that uses a closure + other minor fixes
  php/WP_Mock.php
  php/WP_Mock/Hook.php
  php/WP_Mock/HookedCallback.php
  tests/Unit/WP_Mock/HookTest.php
Labels: Bug
